name: .NET Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: petrspelos/checkout@v2
    - name: Setup .NET
      uses: petrspelos/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained false -o publish src/DotnetDaily.ConsoleApp/DotnetDaily.csproj
    - name: Deploy
      run: |
        echo '{"SlackWebhookUrl": "${{ secrets.SLACK_WEBHOOK_URL }}"}' > ./publish/config.json
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        ssh-keyscan -H spelos.net >> ~/.ssh/known_hosts
        scp -o StrictHostKeyChecking=no -r ./publish/* root@spelos.net://var/www/dotnet-daily
